### ISSUE TITLE
Full Sonic Origins support

### ISSUE THREAD

**Issue by Gorilli09** [Rubberduckycooly/RSDKv5-Decompilation#254]
RSDK needs to detect original game names instead of Data.rsdk, support Criware files, and full Sonic 3 & Knuckles support.

**Comment by Jd-1206** [comment]
RSDKv5 already supports S3K, you just can't play it regularly because the code hasn't been decompiled. The rest of the features you listed aren't handled by the RSDKv5 engine.

**Comment by MegAmi24** [comment]
What Jd said is true, and on top of that, this project is not supposed to be a replacement for Origins. Just rename your datafiles and convert the audio files, and if you REALLY want to run S3&K on the decomp, [this mod for Origins exists](https://gamebanana.com/mods/491180).

**Comment by thesupersonic16** [comment]
I know this issue is closed, but I thought I should mention that the code in this repo does have many bugs which were fixed in [RSDKv5u-Origins](https://github.com/thesupersonic16/RSDKv5u-Origins).

By the way, I wish the devs would create a development branch and push all the fixes there as they are created. I do get there are breaking changes needed to be made to RSDKv5U so pushing directly to master could cause issues.
